# Generated by Django 6.0.4 on 2026-05-17 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(unique=True, verbose_name='회차')),
                ('winning_numbers', models.CharField(blank=True, max_length=50, null=True, verbose_name='당첨 번호 (쉼표로 구분)')),
                ('bonus_number', models.IntegerField(blank=True, null=True, verbose_name='보너스 번호')),
                ('draw_date', models.DateTimeField(blank=True, null=True, verbose_name='추첨 일시')),
                ('is_drawn', models.BooleanField(default=False, verbose_name='추첨 완료 여부')),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=50, verbose_name='선택 번호 (쉼표로 구분)')),
                ('is_automatic', models.BooleanField(default=True, verbose_name='자동 여부 (True:자동 / False:수동)')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='구매 일시')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='당첨 등수')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottoround', verbose_name='해당 회차')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
        ),
    ]
