# Generated by Django 6.0.4 on 2026-05-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(unique=True, verbose_name='회차')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('num3', models.IntegerField()),
                ('num4', models.IntegerField()),
                ('num5', models.IntegerField()),
                ('num6', models.IntegerField()),
                ('bonus_num', models.IntegerField()),
                ('draw_date', models.DateTimeField(auto_now_add=True, verbose_name='추첨일')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_round', models.IntegerField(verbose_name='응모 회차')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('num3', models.IntegerField()),
                ('num4', models.IntegerField()),
                ('num5', models.IntegerField()),
                ('num6', models.IntegerField()),
                ('is_auto', models.BooleanField(default=True, verbose_name='자동 여부')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='구매일')),
            ],
        ),
        migrations.RemoveField(
            model_name='lottoticket',
            name='round',
        ),
        migrations.RemoveField(
            model_name='lottoticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='LottoRound',
        ),
        migrations.DeleteModel(
            name='LottoTicket',
        ),
    ]
